name: Nightly build

on:
  # Enable a workflow to be triggered manually
  workflow_dispatch:

  # Schedule docs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # Check cron syntax here https://crontab.guru/
  # Schedule to run this workflow at 00:00 UTC every tuesday to saturday
  schedule:
    - cron: '0 0 * * 2-6'

jobs:
  build:
    uses: futuredapp/.github/.github/workflows/ios-selfhosted-nightly-build.yml@main

    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
      APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      JIRA_CONTEXT: ${{ secrets.JIRA_CONTEXT }}